openapi: '3.0.2'
info:
  version: '1.0.0'
  title: Mod.R6RU

paths:
# Gateway ping
  /echo:
    get:
      summary: Echo
      operationId: echo
      parameters:
        - name: msg
          in: query
          description: Message
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Echo
          content:
            'text/plain':
              schema:
                type: "string"
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          'Content-Type': "text/plain"
        content:
          'text/plain': "Hello again, {msg}!\n"
# Function ping
  /test:
    get:
      responses: { '200' }
      x-yc-apigateway-integration:
        $ref: '#/components/x-yc-apigateway-integrations/BaseFunction'

    post:
      responses: { '200' }
      x-yc-apigateway-integration:
        $ref: '#/components/x-yc-apigateway-integrations/BaseFunction'

# Discord outgoing webhook
  /bot:
    post:
      responses: { '200' }
      x-yc-apigateway-integration:
        $ref: '#/components/x-yc-apigateway-integrations/BaseFunction'

components:
  x-yc-apigateway-integrations:
    BaseFunction:
      type: cloud_functions
      function_id: ${function_id}
      service_account_id: ${service_account_id}